### ISSUE TITLE
Missing test_plans

### ISSUE THREAD

**Issue by VishnuDuttSharma** [SMARTlab-Purdue/DynaCon#1]
I get the following error when I run LLM:

```
Traceback (most recent call last):
  File "scripts/run_llm_with_ROS.py", line 128, in <module>
    for file in os.listdir(f"./data/{args.test_set}"):
FileNotFoundError: [Errno 2] No such file or directory: './data/test_plans'
```

Could you please share these files or share the details on how to generate them?

**Comment by yaofulan** [comment]
I met the same problem as you, 
with_ROS.py --expt-name test
Traceback (most recent call last):
  File "/home/csc/catkin_ws/src/DynaCon/scripts/run_llm_with_ROS.py", line 128, in <module>
    for file in os.listdir(f"./data/{args.test_set}"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/test_plans'

do not know how to get this file.

**Comment by yaofulan** [comment]
> I get the following error when I run LLM:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/run_llm_with_ROS.py", line 128, in <module>
>     for file in os.listdir(f"./data/{args.test_set}"):
> FileNotFoundError: [Errno 2] No such file or directory: './data/test_plans'
> ```
> 
> Could you please share these files or share the details on how to generate them?

I wonder have you solved this problem yet?

**Comment by VishnuDuttSharma** [comment]
Unfortunately, no. Still waiting for an update to the repo.
